import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/layout/nav";
import Footer from "@/layout/footer";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Full day - Gobierno TI - Sistemas Promoción XXV",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
            >
                <Nav />
                {children}
                <Footer />
            </body>
        </html>
    );
}
